 eureka:
 
     instance:
         prefer-ip-address: true
         status-page-url: http://192.168.101.70:8762/swagger-ui.html
         metadata-map:
             getUserList: {"url":"user/getAll","desc":"获取用户列表","method":"get"}
             getUserById: {"url":"user/getUserById","desc":"根据用户id获取用户信息","method":"get"}
             updateUser: {"url":"user/update","desc":"更新用户信息","method":"put"}
     client:
         serviceUrl:
             defaultZone: http://192.168.101.70:8761/eureka/
 server:
     port: 8762
 spring:
     application:
         name: service-helloworld
